spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update